# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bbc98d00b55d9339d81596fed1fee931d1091ce437f11c585e365161db2a64fbfc3f2a7509b08fc6b5a4b70f2d0b510eb85a91929d9e66e695411790e0ee29bf

test:
  secret_key_base: 8efc5895095b995bff96780799ac2a599ee8c0914c06482c6601f7352e5018339beac50aee7c24b63230291be65021095e8bb5047399bf92ba2b590a6cd245d7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
